### ISSUE TITLE
ES6 Solution?

### ISSUE THREAD

**Issue by crisward** [tyxla/remove-accents#23]
Found this library while looking for a solution to this problem. Also discovered that ES6 can now do the following. I realise this library is 3 years old, so incase anyone else need a one line solution instead of another dependency.

```javascript
"ÀÁÂÃÄÅ".normalize("NFD").replace(/[\u0300-\u036f]/g, "")
//outputs AAAAAA
```
Note the above method only works with accents, not  none accented characters eg - `Æ`

**Comment by tyxla** [comment]
Thank you for this one! Closing since no action is necessary.
