### ISSUE TITLE
Accents not removed in Greek alphabet

### ISSUE THREAD

**Issue by mcsf** [tyxla/remove-accents#52]
Observed here: https://github.com/WordPress/gutenberg/pull/61876#discussion_r1611352527

```
> RA.remove( 'φιλε φίλε' )
'φιλε φίλε'
```

Expected output: `φιλε φιλε`.

Or at least that's what I expect as an outsider with only some knowledge of Greek.

**Comment by tyxla** [comment]
Good one - the accented [Iota](https://simple.wikipedia.org/wiki/Iota) is definitely missing. Wanna file a PR? 😅

**Comment by tyxla** [comment]
It appears like a bunch more [Greek diacritics](https://en.wikipedia.org/wiki/Greek_diacritics) exist and are missing. Could be a good addition to the existing supported characters.

**Comment by mcsf** [comment]
I can give it a go at the end of the day, but I think I'll stick to just Modern Greek, which presents a smaller set of combinations to deal with :P

**Comment by mcsf** [comment]
Actually, I just realised that compatibility with WordPress's `remove_accents` is important, and that function doesn't modify Greek diacritics (_cf._ [source](https://core.trac.wordpress.org/browser/tags/6.5.3/src/wp-includes/formatting.php?rev=58115#L1607) — don't be fooled by the alpha-looking thing, it's part of the Latin set).

So I'll close this one.
